### PR TITLE
Created the new Homepage

### PR DESCRIPTION
**Pull request by jonddon**
I created the new homepage

### CODE REVIEW

**Comment by tayormi** [comment]
Screenshot at Jun 18 18-15-54

Hi, @jonddon, the app didn't build. Check the error from Vercel.

**Comment by tayormi** [comment]
Same error.

Here is the logs.
`

18:27:18.115 | Cloning github.com/codeclannigeria/codeclannigeria-frontend (Branch: master, Commit: 5ae559d)
-- | --
18:27:19.177 | Cloning completed: 1.062s
18:27:19.238 | Analyzing source code...
18:27:20.704 | Installing build runtime...
18:27:23.332 | Build runtime installed: 2.628s
18:27:26.296 | Looking up build cache...
18:27:27.048 | Build cache found. Downloading...
18:27:30.665 | Build cache downloaded [45.56 MB]: 3617.121ms
18:27:31.831 | Detected package.json
18:27:31.831 | Installing dependencies...
18:27:35.431 | npm WARN conflict A git conflict was detected in package-lock.json. Attempting to auto-resolve.
18:27:35.432 | npm WARN conflict To make this happen automatically on git rebase/merge, consider using the npm-merge-driver:
18:27:35.432 | npm WARN conflict $ npx npm-merge-driver install -g
18:27:38.062 | npm WARN deprecated babel-eslint@7.2.3: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
18:27:38.296 | npm WARN deprecated eslint-loader@1.9.0: This loader has been deprecated. Please use eslint-webpack-plugin
18:27:38.433 | npm WARN deprecated extract-text-webpack-plugin@3.0.2: Deprecated. Please use https://github.com/webpack-contrib/mini-css-extract-plugin
18:27:38.437 | npm WARN deprecated html-webpack-plugin@2.29.0: out of support
18:27:38.643 | npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
18:27:38.858 | npm WARN deprecated browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist &gt;3.0 config used in other tools.
18:27:39.733 | npm WARN deprecated sw-precache@5.2.1: Please migrate to Workbox: https://developers.google.com/web/tools/workbox/guides/migrations/migrate-from-sw
18:27:39.872 | npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
18:27:40.364 | npm WARN deprecated core-js@2.6.12: core-js@&lt;3.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Please, upgrade your dependencies to the actual version of core-js.
18:27:41.688 | npm WARN deprecated sw-toolbox@3.6.0: Please migrate to Workbox: https://developers.google.com/web/tools/workbox/guides/migrations/migrate-from-sw
18:27:42.249 | npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
18:27:42.290 | npm WARN deprecated browserslist@1.7.7: Browserslist 2 could fail on reading Browserslist &gt;3.0 config used in other tools.
18:28:06.549 | npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
18:28:06.621 | npm WARN deprecated har-validator@5.1.5: this library is no longer supported
18:28:06.697 | npm WARN deprecated uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
18:28:33.848 | &gt; core-js@2.6.12 postinstall /vercel/path0/node_modules/core-js
18:28:33.848 | &gt; node -e "try{require('./postinstall')}catch(e){}"
18:28:33.943 | Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
18:28:33.943 | The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
18:28:33.943 | &gt; https://opencollective.com/core-js
18:28:33.943 | &gt; https://www.patreon.com/zloirock
18:28:33.943 | Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
18:28:34.220 | &gt; uglifyjs-webpack-plugin@0.4.6 postinstall /vercel/path0/node_modules/uglifyjs-webpack-plugin
18:28:34.220 | &gt; node lib/post_install.js
18:28:35.624 | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.1.3 (node_modules/react-scripts/node_modules/fsevents):
18:28:35.624 | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
18:28:35.629 | npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.2 (node_modules/chokidar/node_modules/fsevents):
18:28:35.629 | npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
18:28:35.637 | npm WARN rc-picker@1.10.4 requires a peer of dayjs@^1.8.18 but none is installed. You must install peer dependencies yourself.
18:28:35.645 | npm WARN bootstrap@4.6.0 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
18:28:35.653 | npm WARN bootstrap@4.6.0 requires a peer of popper.js@^1.16.1 but none is installed. You must install peer dependencies yourself.
18:28:35.675 | npm WARN ajv-keywords@3.5.2 requires a peer of ajv@^6.9.1 but none is installed. You must install peer dependencies yourself.
18:28:35.679 | added 812 packages from 378 contributors, removed 533 packages, updated 437 packages and moved 48 packages in 63.247s
18:28:36.798 | 58 packages are looking for funding
18:28:36.798 | run `npm fund` for details
18:28:37.082 | Running "npm run build"
18:28:37.355 | &gt; codeclannigeria-frontend@0.1.0 build /vercel/path0
18:28:37.355 | &gt; react-scripts build
18:28:38.396 | Creating an optimized production build...
18:29:04.158 | Failed to compile.
18:29:04.159 | ./src/index.css
18:29:04.159 | Module build failed: BrowserslistError: Unknown browser query `dead`
18:29:04.160 | at Array.forEach (&lt;anonymous&gt;)
18:29:04.203 | npm ERR! code ELIFECYCLE
18:29:04.203 | npm ERR! errno 1
18:29:04.207 | npm ERR! codeclannigeria-frontend@0.1.0 build: `react-scripts build`
18:29:04.207 | npm ERR! Exit status 1
18:29:04.207 | npm ERR!
18:29:04.207 | npm ERR! Failed at the codeclannigeria-frontend@0.1.0 build script.
18:29:04.207 | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
18:29:04.213 | npm ERR! A complete log of this run can be found in:
18:29:04.213 | npm ERR!     /vercel/.npm/_logs/2021-06-18T17_29_04_208Z-debug.log
18:29:04.227 | Error: Command "npm run build" exited with 1

`

**Comment by tayormi** [comment]
Deployment failed.

**Comment by tayormi** [comment]
Same problem Pastor John.

**Comment by jonddon** [comment]
> Same problem Pastor John.

ok. I go let you know when i fix am

**Pull request merged**
